965 fishing points tracks
GlobalFishingWatch/api-vessels pull request #2
Opened 2019-02-12 22:45 UTC by andres-arana

Connects https://github.com/GlobalFishingWatch/GFW-Tasks/issues/965
Connects https://github.com/GlobalFishingWatch/GFW-Tasks/issues/961

These changes add a new parameter to the tracks API, `features`, which allows the client to request additional features besides simple tracks in the resulting GeoJSON. For now, the following values are supported:

* `fishing`: Adds additional features to the root `FeatureCollection` containing the points at which fishing was detected in the tracks.
* `speed` and `course`: Adds additional properties to the `coordinateProperties` of each track which include per-point speed and course respectively.

By default, if the parameter is empty no extra information besides the track will be returned.

2019-02-13 14:13 UTC, enriquetuya requested changes

2019-02-13 14:13 UTC, enriquetuya commented on src/data/tracks.js
> +        filter(([score, coordinate]) => score > 0.5),
Why score > `0.5`? We only have scores 0/1 now.

2019-02-13 14:34 UTC, andres-arana commented on src/data/tracks.js
> +        filter(([score, coordinate]) => score > 0.5),
Yeah, but javascript only has floats and `score === 1.0` is a bit brittle due to how floats are represented in memory.

2019-02-14 10:49 UTC, nerik commented
Just one thing: timestamps are still in ISO instead of ms. 
Apart from that, looks good 👍
It will be so much easier to work / debug / add features with GeoJSON

2019-02-15 16:47 UTC, merged